### ISSUE TITLE
YCB-render Error with "Segmentation fault" due to "eglQueryDevicesEXT"

### ISSUE THREAD

**Issue by greatwallet** [NVlabs/PoseRBPF#2]
## Error
I have successfully build `ycb_render` locally.
When running `python ycb_renderer.py` or `./build/query_devices` or `./build/test_device`, it bumps up with `Segmentation fault (core dumped)`. After debugging, I found the problem to be exactly the function `eglQueryDevicesEXT` which raises the error.

BTW, I printed out the result of `egl_error` which is equal to `EGL_SUCCESS` and seems not the problem.
I also tried to print the result of `gladLoadGL(eglGetProcAddress)`, but the result is `false`, so it might have something to do with gpu stuff, I guess?

## System
* Ubuntu 16.04
* NVCC 10.0
* pytorch 1.4.0 + cudatoolkit 100
* python 3.8

**Comment by greatwallet** [comment]
Solved by re-installing the environment

**Comment by lizolson1** [comment]
Do you mean re-installing the pose_rbpf_env conda environment?

**Comment by greatwallet** [comment]
> Do you mean re-installing the pose_rbpf_env conda environment?
> 
> Also the ycb_render README says:
> #additionally, you need to install nvidia OpenGL drivers and make them visible
> export LD_LIBRARY_PATH=/usr/lib/nvidia-:$LD_LIBRARY_PATH
> 
> What did you do for these steps? Thank you!

Yes, exactly

**Comment by Spj-Zhao** [comment]
I re-install the pose_rbpf_env conda environment,but it also bumps up with Segmentation fault (core dumped).
